<?php
/**
 * @file
 * Code for the GSB Feature Event Display feature.
 */

include_once 'gsb_feature_event_display.features.inc';

/**
 * Implementation of hook_form_FORM_ID_alter()
 *
 * Provides customizations to the views content type settings form
 */
function gsb_feature_event_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form["display_settings"])) {
    if (isset($form["display_settings"]["view_settings"])) {
      $form["display_settings"]["view_settings"]['#access'] = FALSE;
    }
    if (isset($form["display_settings"]["header_type"])) {
      $form["display_settings"]["header_type"]['#access'] = FALSE;
    }
  }
  if (isset($form["content_settings"])) {
    $form["content_settings"]['#access'] = FALSE;
  }
}

/**
 * Implementation of hook_module_implements_alter()
 */
function gsb_feature_event_display_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if (isset($implementations['gsb_feature_event_display'])) {
      $group = $implementations['gsb_feature_event_display'];
      unset($implementations['gsb_feature_event_display']);
      $implementations['gsb_feature_event_display'] = $group;
    }
  }
}

/**
 * Implements hook_field_extra_fields().
 */
function gsb_feature_event_display_field_extra_fields() {
  $extra = array();
  // Add an extra field for iCal links.
  $extra['node']['event']['display']['gsb_feature_event_display_ical'] = array(
    'label' => t('iCal URL'),
    'description' => t('A link to an iCal event'),
    'weight' => 0,
  );
  return $extra;
}

/**
 * Implements hook_node_view().
 */
function gsb_feature_event_display_node_view($node, $view_mode, $langcode) {
  // Only process events.
  if ($node->type != 'event') {
    return;
  }

  // Add a link for the iCal event.
  $node->content['gsb_feature_event_display_ical'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'event-ical-link',
      ),
    ),
    'link' => array(
      '#type' => 'link',
      '#title' => t('Add to My Calendar'),
      '#href' => 'events/ical/' . $node->nid . '/event.ics',
      '#attributes' => array(
        'class' => array(
          'green-rounded-button',
        ),
      ),
    ),
  );
}
